name: build module

on: [push]

jobs:
  build-and-publish-module:
    name: Run build and upload artifacts
    runs-on: windows-latest
    steps:
      - name: Check out repository code
      - uses: actions/checkout@v4

